[[models]]
id = "llama3.1:70b-instruct-fp16"
runner = "ollama"
precision = "fp16"
approx_bytes = 151000000000      # file + headroom (≈141 GB weights + margin)
min_ram_bytes = 170000000000     # ~170 GB recommended

[[models]]
id = "llama3.1:8b-instruct-fp16"
runner = "ollama"
precision = "fp16"
approx_bytes = 17000000000       # ~17 GB
min_ram_bytes = 22000000000      # ~22 GB suggested

[[models]]
id = "gpt-oss:20b"
runner = "ollama"
precision = "fp16/mixed"
approx_bytes = 15000000000      # ~14–15 GB on disk (Ollama tag)
min_ram_bytes = 16000000000     # 16 GB minimum; 1.2× is ideal for VRAM

[[models]]
id = "qwen2.5:7b-instruct-q8_0"
runner = "ollama"
precision = "q8_0"
approx_bytes = 9000000000        # ~9 GB
min_ram_bytes = 12000000000      # ~12 GB suggested

[[models]]
id = "phi3:mini-3.8b-q8_0"
runner = "ollama"
precision = "q8_0"
approx_bytes = 5000000000        # ~5 GB
min_ram_bytes = 8000000000       # ~8 GB suggested

[[models]]
id = "mlc-ai/Llama-3.2-1B-Instruct-q0f16-MLC"
runner = "mlc"
precision = "fp16"
approx_bytes = 2500000000        # ~2.5 GB phone/tablet artifact
min_ram_bytes = 3000000000

[[models]]
id = "mlc-ai/Llama-3.2-3B-Instruct-q0f16-MLC"
runner = "mlc"
precision = "fp16"
approx_bytes = 6000000000
min_ram_bytes = 7000000000

[[wikis]]
name = "wikipedia_en_all_nopic_2025-08.zim"
url = "https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_nopic_2025-08.zim"
approx_bytes = 46000000000
sha256 = "f8ff1e22cc2d1811620837ffb07d9bf85fdd1e4e7659f4d80c481337b52a62b1"

[[wikis]]
name = "wikipedia_en_all_maxi_2025-08.zim"
url = "https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2025-08.zim"
approx_bytes = 119000000000
sha256 = "3aa55399c5afa6eb5c2477194e0d022c0527616408bc644c2224ed328da62dfb"

[[wikis]]
name = "wikipedia_en_mini_2025-08.zim"
url = "https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_mini_2025-06.zim"
approx_bytes = 13000000000
sha256 = "e9709b6f687eae6d268a73f7b68aa3ac3e47ba076f7fe9f7a15e0ae019814a78"

# Fallback mirrors or torrents—user can add/override these; installer tries all.
[[sources]]
label = "Kiwix primary"
url = "https://download.kiwix.org/zim/wikipedia/"

[[sources]]
label = "Mirror (Fau)"
url = "https://ftp.fau.de/kiwix/zim/wikipedia/"

[[sources]]
label = "IPFS gateway (user-provided CID)"
url = "ipfs://<CID>"